use handlebars.compile instead of handlebars.template
The chain of handlebars.template and handlebars.precompile doesn't seem
to work completely as advertised, throwing an error:

    /usr/local/lib/node_modules/raml-fleece/node_modules/handlebars/dist/cjs/handlebars/runtime.js:48
        throw new _Exception2['default']('Unknown template object: ' +
    typeof temp
              ^
    Error: Unknown template object: string
        at Object.template
    (/usr/local/lib/node_modules/raml-fleece/node_modules/handlebars/dist/cjs/handlebars/runtime.js:48:11)
        at HandlebarsEnvironment.hb.template
    (/usr/local/lib/node_modules/raml-fleece/node_modules/handlebars/dist/cjs/handlebars.runtime.js:46:20)
        at handlebars.compile.preventIndent
    (/usr/local/lib/node_modules/raml-fleece/src/to-html.js:125:29)